// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa05PYVyEuPzJnYNDvzpsOLu20ClNsHN0',
    appId: '1:582387556211:web:dcfc53c8f3dcadf0d2ef06',
    messagingSenderId: '582387556211',
    projectId: 'cogniosisapp',
    authDomain: 'cogniosisapp.firebaseapp.com',
    storageBucket: 'cogniosisapp.firebasestorage.app',
    measurementId: 'G-8J95FEM76F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6DQUhVZND1_p61xfsWP1WlXYiCwwFkM',
    appId: '1:582387556211:android:c818a3de577130f1d2ef06',
    messagingSenderId: '582387556211',
    projectId: 'cogniosisapp',
    storageBucket: 'cogniosisapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjeJiU5JyhsNaIpH2X2ZNHBg4Y_h1ExhI',
    appId: '1:582387556211:ios:da9e4fed3cddd3cdd2ef06',
    messagingSenderId: '582387556211',
    projectId: 'cogniosisapp',
    storageBucket: 'cogniosisapp.firebasestorage.app',
    iosBundleId: 'com.aizen.cogniosisdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjeJiU5JyhsNaIpH2X2ZNHBg4Y_h1ExhI',
    appId: '1:582387556211:ios:da9e4fed3cddd3cdd2ef06',
    messagingSenderId: '582387556211',
    projectId: 'cogniosisapp',
    storageBucket: 'cogniosisapp.firebasestorage.app',
    iosBundleId: 'com.aizen.cogniosisdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa05PYVyEuPzJnYNDvzpsOLu20ClNsHN0',
    appId: '1:582387556211:web:8673154bb21a0c47d2ef06',
    messagingSenderId: '582387556211',
    projectId: 'cogniosisapp',
    authDomain: 'cogniosisapp.firebaseapp.com',
    storageBucket: 'cogniosisapp.firebasestorage.app',
    measurementId: 'G-RRXWJLV4PE',
  );
}
