# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Pods for Run
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
